<?php

namespace Database\Seeders;

use App\Models\News;
use Illuminate\Database\Seeder;

class NewsSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $news = array(
      array('id' => '5', 'locale' => 'ru', 'title' => 'Opening of "JYSK" in Tajikistan', 'slug' => 'otkrytie-pervogo-magazina-jysk-v-tadzhikistane-3', 'content' => '<p>"JYSK" is an international distribution network offering Scandinavian style furniture and household goods. JYSK" is headquartered in Aarhus, Denmark. The company owns the biggest chain of furniture stores in Denmark and is widely presented all over the world. In Tajikistan, the first store of "JYSK" opened on December 17, 2016. In honor of the opening they announced a 20% discount on all goods, as well as held a raffle of gifts among customers. To this day, "JYSK" is the only store in Tajikistan that offers Scandinavian-style goods.&nbsp;<br></p>', 'created_at' => '2022-09-13 05:57:44', 'updated_at' => '2022-10-16 11:59:06', 'date' => '2016-12-17T16:32'),
      array('id' => '6', 'locale' => 'ru', 'title' => 'Opening of "KHONAI MAN" brand', 'slug' => 'otkrytie-otechestvennogo-brenda-honai-man', 'content' => '<p>On March 21, 2017, the domestic brand "Khonai Man" was opened. In honor of the opening, they announced a 20% discount on all goods, and also held a raffle of gifts among customers. "KHONAI MAN" has become the only furniture mall where you can find everything you need for your home. Categories of goods and a wide assortment have become the hallmark of the brand.&nbsp;<br></p>', 'created_at' => '2022-09-13 06:29:00', 'updated_at' => '2022-10-16 11:58:27', 'date' => '2017-03-21T16:50'),
      array('id' => '8', 'locale' => 'ru', 'title' => '"Brand of the Year" 2019.', 'slug' => 'brend-goda', 'content' => '<p>During its operation, the domestic brand "Khonai Man" has won the "Brand of the Year" category 2 times. This is the second time in three years of our work the award has been given. Strong brand recognition, consumer confidence, high quality standards - this is what they pay attention to when selecting the winners. According to the results of all these assessments we were named the brand of the year.<br></p>', 'created_at' => '2022-09-13 07:43:03', 'updated_at' => '2022-10-16 11:47:18', 'date' => '2019-12-19T16:58'),
      array('id' => '10', 'locale' => 'ru', 'title' => '"JYSK/KHONAI MAN" at Siyoma Mall', 'slug' => 'otkrytie-jysk-honai-man-v-tcrc-siema-moll', 'content' => '<p>19.11.2021 "JYSK/KHONAI MAN" was opened in Siyoma Mall<br></p>', 'created_at' => '2022-09-13 11:19:05', 'updated_at' => '2022-10-16 11:33:23', 'date' => '2021-11-19T17:02'),
      array('id' => '12', 'locale' => 'ru', 'title' => 'Opening of "YOVAR" Meat Market', 'slug' => 'otkrytie-myasnogo-marketa-evar-2', 'content' => '<p>The company started its activities in retail business by opening YOVAR Meat Market in Dushanbe, the first specialized meat store in the country, on May 11, 2013.<br></p>', 'created_at' => '2022-09-14 11:07:12', 'updated_at' => '2022-10-16 12:01:36', 'date' => '2013-05-11T17:27'),
      array('id' => '15', 'locale' => 'ru', 'title' => '"Brand of the Year 2017', 'slug' => 'brend-goda-2', 'content' => '<p>We grew and developed thanks to the feedback and wishes of our customers. As a result of our joint efforts "YOVAR" was recognized as the BRAND OF THE YEAR 2017!!! We sincerely congratulate all our esteemed clients and the whole "YOVAR" team!<br></p>', 'created_at' => '2022-09-14 12:56:58', 'updated_at' => '2022-10-16 11:56:44', 'date' => '2017-12-13T17:34'),
      array('id' => '16', 'locale' => 'ru', 'title' => '"Brand of the Year" 2019', 'slug' => 'brend-goda-3', 'content' => '<p>WE are recognized as the "BRAND OF THE YEAR 2019" and awarded with the GOLDEN AWARD!!! The emotions are overwhelming! In 6 years in business - this is our second award - we have been named "BRAND OF THE YEAR" twice already. First of all, we would like to heartily thank our customers-friends who trust us and choose us! THANK YOU FOR BEING WITH US!&nbsp; We have tried and will try to get better and better every time!<br></p>', 'created_at' => '2022-09-14 13:02:03', 'updated_at' => '2022-10-16 11:46:30', 'date' => '2019-12-19T17:40'),
      array('id' => '17', 'locale' => 'ru', 'title' => '"Worthy of the People\'s Trust".', 'slug' => 'dostoynyy-doveriya-naroda', 'content' => '<p>As everyone knows, the award ceremony of "THE PEOPLE\'S TRUST OF THE PEOPLE" was held on May 21! WE have been recognized by Worthy of the People\'s Trust for 2021 and awarded with a GOLDEN AWARD!!! First and foremost, we want to heartily thank our customers-friends who trust us and choose us! THANK YOU FOR BEING WITH US! We have tried and will try to get better and better every time! We sincerely want to express our gratitude to the judges for rating us so highly. Thank you to our partners for forming warm, strong and long-term relationships!<br></p>', 'created_at' => '2022-09-14 13:04:54', 'updated_at' => '2022-10-16 11:40:01', 'date' => '2021-05-21T18:06'),
      array('id' => '18', 'locale' => 'ru', 'title' => 'Opening of Toyota dealer center', 'slug' => 'otkrytie-dilerskogo-centra-toyota-v-tadzhikistane', 'content' => '<p>The official opening of the official Toyota dealer center in Tajikistan took place. Taj Motors LLC is the official and only dealer of "TOYOTA MOTOR CORPORATION" in the Republic of Tajikistan since July 5, 2013. Taj Motors LLC is a modern 3S complex built in accordance with all standards of "TOYOTA MOTOR CORPORATION". Building of the showroom, accesses to the center, transport interchange, separate parking for visitors of the showroom and customers of the service fully meet the latest requirements of "TOYOTA MOTOR CORPORATION". Taj Motors LLC is a modern progressive enterprise, capable of solving car maintenance and repair tasks of any category of complexity, which distinguishes it from its competitors.<br></p>', 'created_at' => '2022-09-14 13:10:47', 'updated_at' => '2022-10-16 12:00:45', 'date' => '2013-07-05T15:27'),
      array('id' => '19', 'locale' => 'ru', 'title' => 'Community care', 'slug' => 'zabota-ob-obshchestve', 'content' => '<p><span style="font-size: 1em;">Unique model range: Corolla, Camry, CH-R, Rav4, Hilux, Hiace, Land Cruiser Prado, Land Cruiser 300. All presented cars are specially adapted to the difficult road and climatic conditions of Tajikistan.</span></p>', 'created_at' => '2022-09-14 13:41:25', 'updated_at' => '2022-10-16 11:37:13', 'date' => '2021-06-05T13:13'),
      array('id' => '20', 'locale' => 'ru', 'title' => 'Employee certification', 'slug' => 'sotrudniki-nashe-vse', 'content' => '<p>Сертификация сотрудников дилерского центра Тойота, это долгий и трудоемкий процесс. Сотрудники должны пройти курс тренингов, и только после этого сдать экзамен. Если экзамен сдан, сотрудник дилерского центра будет сертифицирован и получит специальный диплом Тойота. В эти дни благодаря нашему дистрибьютору Toyota Central Asia official, были проведены тренинги по Тойота Сервис Менеджмент. Тойота Сервис Менеджмент (TСM) — всеобъемлющая программа развития послепродажного обслуживания в дилерских центрах Тойота по всему миру. Основная цель TСM — достижение максимального уровня удовлетворенности клиентов качеством предоставляемых им услуг.<br></p>', 'created_at' => '2022-09-14 13:44:00', 'updated_at' => '2022-10-16 11:19:28', 'date' => '2022-07-22T18:10'),
      array('id' => '21', 'locale' => 'ru', 'title' => '"Toyota Dream Car".', 'slug' => 'socialnaya-otvetstvennost', 'content' => '<p>Toyota Center Dushanbe "TAJ MOTORS" held a ceremony awarding the winners of the regional stage of the 9th International Toyota Dream Car Art Contest for Children (Toyota Dream Car Contest).<br></p>', 'created_at' => '2022-09-14 13:49:19', 'updated_at' => '2022-10-16 12:00:21', 'date' => '2015-02-21T18:16'),
      array('id' => '23', 'locale' => 'ru', 'title' => 'Top 100 Successful Women."', 'slug' => 'socialnaya-otvetstvennost-2', 'content' => '<p>"JYSK/KHONAI MAN" actively supports social projects. At the recent "Top 100 Successful Women" awards we sponsored 30 thousand somoni to the project.&nbsp;&nbsp;<br></p>', 'created_at' => '2022-09-19 09:34:37', 'updated_at' => '2022-10-16 11:35:42', 'date' => '2021-06-05T18:22'),
      array('id' => '25', 'locale' => 'ru', 'title' => 'We Remember! We are proud!', 'slug' => 'socialnaya-otvetstvennost-3', 'content' => '<p>"JYSK/KHONAI MAN" has an active charity policy. On Victory Day, we visited WWII veterans, thanked them and gave them specialized gifts from our store.<br></p>', 'created_at' => '2022-09-19 10:01:09', 'updated_at' => '2022-10-16 11:53:46', 'date' => '2018-05-09T18:25'),
      array('id' => '26', 'locale' => 'ru', 'title' => '"Give the Gift of Warmth" event', 'slug' => 'socialnaya-otvetstvennost-4', 'content' => '<p>The "Give the Gift of Warmth" action. Our compatriots brought to the store "JYSK/KHONAI MAN" old blankets, pillows, blankets, bed linens, baby clothes, shoes, towels, clothes, and in return we gave 11% discount on the whole range. All collected items were given to the volunteer group "Do Good Tajikistan".<br></p>', 'created_at' => '2022-09-19 10:08:02', 'updated_at' => '2022-10-16 11:52:33', 'date' => '2018-11-03T18:29'),
      array('id' => '28', 'locale' => 'ru', 'title' => 'Children Protection Day', 'slug' => 'socialnaya-otvetstvennost-5', 'content' => '<p><span style="font-size: 1em;">Every year we organize free children\'s parties on the terrace of our "JYSK / Honai man" store, where children were given the opportunity to play, dance, draw and have fun.</span><br></p>', 'created_at' => '2022-09-19 10:17:31', 'updated_at' => '2022-10-16 11:50:17', 'date' => '2019-06-01T18:34'),
      array('id' => '29', 'locale' => 'ru', 'title' => 'Exhibition of young artists', 'slug' => 'socialnaya-otvetstvennost-6', 'content' => '<p>In 2018, "JYSK/KHONAI MAN" held an exhibition of young artists where they invited ambassadors and representatives from other countries. Each young artist had the opportunity to show, tell, and sell their paintings.&nbsp;<br></p>', 'created_at' => '2022-09-21 11:58:40', 'updated_at' => '2022-10-16 11:51:45', 'date' => '2018-11-09T18:41'),
      array('id' => '31', 'locale' => 'ru', 'title' => '"Stop Violence Against Women."', 'slug' => 'socialnaya-otvetstvennost-7', 'content' => '<p>"JYSK/KHONAI MAN" supported UNDP\'s initiative and supported the "Stop Violence Against Women" campaign. In support of the action, our female employees wore orange headscarves as a sign of support for the action.<br></p>', 'created_at' => '2022-09-21 12:15:58', 'updated_at' => '2022-10-16 11:57:20', 'date' => '2017-11-24T18:49'),
      array('id' => '33', 'locale' => 'ru', 'title' => 'Ruins of Ajinatepp', 'slug' => 'socialnaya-otvetstvennost-8', 'content' => '<p><span style="font-size: 1em;">The «JYSK/Honaiman» store helped organize a trip for cultural studies students to the ruins of Ajinateppa.</span></p>', 'created_at' => '2022-09-21 12:24:30', 'updated_at' => '2022-10-16 11:24:56', 'date' => '2022-03-03T18:54'),
      array('id' => '40', 'locale' => 'ru', 'title' => 'We Remember! We are proud!', 'slug' => 'zabota-ob-obshchestve-10', 'content' => '<p>Every year "YOVAR" team congratulates veterans of the Great Patriotic War on the 9th of May! Their work and contribution is invaluable! We owe our peaceful sky over our heads to them! No one is forgotten, nothing is forgotten!<br></p>', 'created_at' => '2022-09-21 13:25:36', 'updated_at' => '2022-10-16 11:20:40', 'date' => '2022-05-09T19:15'),
      array('id' => '42', 'locale' => 'ru', 'title' => 'Knowledge Partner - KHIRAD', 'slug' => 'vo-vseh-supermarketah-evar-my-prodaem-samye-imenitye-mirovye-bestsellery-na-tadzhikskom-yazyke', 'content' => '<p>The world\'s bestselling books on business and not only business are available in Tajik language in all "YOVAR" supermarkets with the support of our partner "KHIRAD"!</p><p>You can buy fresh products at an affordable price, and you can also take with you an informative book for self-development.</p>', 'created_at' => '2022-09-24 09:45:07', 'updated_at' => '2022-10-16 11:45:12', 'date' => '2020-03-05T19:23'),
      array('id' => '47', 'locale' => 'ru', 'title' => 'Opening of "YOVAR"', 'slug' => 'otkrytie-3', 'content' => '<p>The 12th "YOVAR" in "Siyoma Mall" was opened.<br></p>', 'created_at' => '2022-09-24 10:24:19', 'updated_at' => '2022-10-16 11:32:16', 'date' => '2021-11-20T19:41'),
      array('id' => '48', 'locale' => 'ru', 'title' => 'Opening of "YOVAR"', 'slug' => 'otkrytie-4', 'content' => '<p>В городе Душанбе открылся наш новый супермаркет &nbsp;«ЁВАР» под №11. По адресу: г. Душанбе, проспект Рудаки 177<br></p>', 'created_at' => '2022-09-24 10:27:27', 'updated_at' => '2022-10-16 11:35:06', 'date' => '2021-07-17T19:50'),
      array('id' => '53', 'locale' => 'ru', 'title' => 'Milli\'s Confectionery House', 'slug' => 'konditerskiy-dom-milli', 'content' => '<p>On the basis of "YOVAR" a subdivision was opened - "Milli" Confectionery House.<br></p>', 'created_at' => '2022-09-24 11:47:22', 'updated_at' => '2022-10-16 11:59:45', 'date' => '2016-12-16T19:54'),
      array('id' => '56', 'locale' => 'ru', 'title' => 'Shopping in installments', 'slug' => 'zabota-ob-obshchestve-14', 'content' => '<p>Now you have an opportunity to pay for your purchases at all "YOVAR" supermarkets with "SALOM Card" from our partner "Alif Bank". Make shopping in our supermarkets profitable and convenient!<br></p>', 'created_at' => '2022-09-26 12:36:54', 'updated_at' => '2022-10-16 11:44:41', 'date' => '2020-08-28T11:50'),
      array('id' => '57', 'locale' => 'ru', 'title' => 'Children\'s Chess Tournament', 'slug' => 'socialnaya-otvetstvennost-9', 'content' => '<p>Our First Children\'s Amateur Chess Tournament took place on the territory of "YOVAR-1" supermarket! The tournament was held in a fun and friendly atmosphere. In the end - the strongest won - Yusupov Azimjon, who became the owner of the certificate in the amount of 800 somoni!<br></p>', 'created_at' => '2022-09-26 12:57:14', 'updated_at' => '2022-10-16 11:47:48', 'date' => '2019-07-20T15:51'),
      array('id' => '58', 'locale' => 'ru', 'title' => '"Little pigeons can carry great messages".', 'slug' => 'zabota-ob-obshchestve-15', 'content' => '<p>Organizing a children\'s festival: " Little pigeons can carry great messages ". Especially for our littlest, sweetest, most important in our life’s children, the company "YOVAR" in honor of CHILDREN\'S DAY on June 8 will organize a CHILDREN\'S FESTIVAL " Little pigeons can carry great messages ".<br></p>', 'created_at' => '2022-09-26 13:13:57', 'updated_at' => '2022-10-16 11:48:48', 'date' => '2019-06-08T16:15'),
      array('id' => '68', 'locale' => 'ru', 'title' => 'Helping organize an ethno-camp', 'slug' => 'socialnaya-otvetstvennost-10', 'content' => '<p>Студенты кафедры культурологии РТСУ отправились в Искандеркуль, при финансовой поддержке сети супермаркетов&nbsp; «ЁВАР». Мы во многом помогли организовать летний этнолагерь "Мы разные, но мы вместе."<br><br></p>', 'created_at' => '2022-09-27 06:10:17', 'updated_at' => '2022-10-16 11:20:06', 'date' => '2022-06-11T16:08'),
      array('id' => '69', 'locale' => 'ru', 'title' => 'Excursion-training in Chiluchorchashma', 'slug' => 'socialnaya-otvetstvennost-11', 'content' => '<p><span style="font-size: 1em;">Excursion-training in Chiluchorchashma. On May 8, 2022, cultural studies students of RTSU, with the financial support of Taj Motors </span></p><p><span style="font-size: 1em;">LLC (Taj-Motors), the only official dealer of Toyota Motor Corporation in Tajikistan, were able to visit one of the sacred places </span></p><p><span style="font-size: 1em;">in Tajikistan.</span><br></p>', 'created_at' => '2022-09-27 06:19:16', 'updated_at' => '2022-10-16 11:22:48', 'date' => '2022-05-08T16:19'),
      array('id' => '70', 'locale' => 'ru', 'title' => 'Launch of the Trade-in Program', 'slug' => 'zabota-ob-obshchestve-16', 'content' => '<p>Toyota "Taj Motors" is pleased to announce the launch of the Trade-in program.</p><p>The Trade-in program is an opportunity to exchange your current car for a new Toyota at an official Toyota dealer center.</p>', 'created_at' => '2022-09-27 06:27:15', 'updated_at' => '2022-10-16 11:40:37', 'date' => '2020-11-25T11:58'),
      array('id' => '71', 'locale' => 'ru', 'title' => 'Installment for car repairs', 'slug' => 'zabota-ob-obshchestve-17', 'content' => '<p>Keeping your car in excellent technical condition with us has become even easier. We offer you a unique service together with Alif Bank - an interest-free installment plan for 12 months to repair your car. Trust your car in good hands.</p><p><br></p><p>We are waiting for you at: Dushanbe, Avenue. Khuvaydulloeva 377/1 (landmark: behind the State Motor Vehicle Inspectorate, 33mkr)</p>', 'created_at' => '2022-09-27 06:33:21', 'updated_at' => '2022-10-16 11:41:14', 'date' => '2020-10-23T12:26'),
      array('id' => '83', 'locale' => 'ru', 'title' => 'New warehouse complex', 'slug' => 'otkrytie-22', 'content' => '<p>"DUSTY PHARMA" a new warehouse complex in Sughd Region, started operations.<br></p>', 'created_at' => '2022-09-27 13:04:32', 'updated_at' => '2022-10-16 11:57:58', 'date' => '2017-07-19T19:57'),
      array('id' => '84', 'locale' => 'ru', 'title' => 'Customer care', 'slug' => 'klient-orientirovannost-4', 'content' => '<p>The company "Dusty Pharma" purchased more than 50 new logistics vehicles.<br></p>', 'created_at' => '2022-09-27 13:14:50', 'updated_at' => '2022-10-16 11:53:08', 'date' => '2018-10-13T20:00'),
      array('id' => '87', 'locale' => 'ru', 'title' => '"YOVAR" new format', 'slug' => 'zabota-ob-obshchestve-18', 'content' => '<p>Innovative design. New refrigeration technology, as well as food storage through ultraviolet light, which not only kills germs and bacteria from the products, but also prevents contamination and spread to other products. Seating areas right in the supermarket, where the customer can get coffee to his taste and freshly baked pastries of national cuisine from a traditional tandoor. And also refresh yourself with a smoothie made from natural ingredients, which will be prepared in a couple of minutes right in front of you.<br></p>', 'created_at' => '2022-09-27 13:24:41', 'updated_at' => '2022-10-16 11:25:53', 'date' => '2022-02-04T19:05'),
      array('id' => '88', 'locale' => 'ru', 'title' => 'Development of bilateral relations', 'slug' => 'razvitie-dvustoronnih-otnosheniy', 'content' => '<p>On September 27, 2022 Asadullo Rahmonov, Director of "YOVAR" Company and Emre Zeki Karagöl, Extraordinary and Plenipotentiary Ambassador of the Republic of Turkey had a business meeting.</p><p><br></p><p>During the meeting the sides discussed the status and prospects of bilateral relations in the field of food retail, and thanked each other for the close cooperation, support and development of affiliate business.</p><p><br></p><p>Turkish products are actively supplied to Tajikistan, including food products. YOVAR" supermarket chain is one of the leaders in import of dairy, drinking, cheese and other Turkish products in its supermarkets.<br></p><p><br></p><p>It should be noted that at present more than 500 types of Turkish products are presented in "YOVAR" supermarkets.&nbsp;<br></p>', 'created_at' => '2022-10-11 14:47:32', 'updated_at' => '2022-10-16 11:18:30', 'date' => '2022-09-27T19:46'),
      array('id' => '89', 'locale' => 'ru', 'title' => 'Community care', 'slug' => 'community-care', 'content' => '<p><span style="font-size: 1em;">Every year for Ramadan, in addition to discounts in the store, </span></p><p><span style="font-size: 1em;">«JYSK / Honai Man» employees distribute water and fruit every Friday on the street to all those who do not have time to break their fast at home.</span><br></p>', 'created_at' => '2022-10-16 11:08:45', 'updated_at' => '2022-10-16 11:08:45', 'date' => '2018-05-18T16:02')
    );
    foreach ($news as $item) {
      $news = News::create([
        'id' => $item['id'],
        'title' => $item['title'],
        'slug' => $item['slug'],
        'content' => $item['content'],
        'date' => $item['date'],
      ]);
    }
  }
}
